"""add tasks table

Revision ID: 2cf102f64616
Revises: c6d9a05ae9e9
Create Date: 2026-05-01 20:29:42.198974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf102f64616'
down_revision: Union[str, Sequence[str], None] = 'c6d9a05ae9e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('school', 'personal', name='task_category_enum'), nullable=False),
    sa.Column('subtype', sa.Enum('tp', 'homework', 'school_project', 'exam', 'side_project', 'personal_todo', 'admin', 'learning', 'other', name='task_subtype_enum'), nullable=False),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'done', name='task_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='task_priority_enum'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_category'), 'tasks', ['category'], unique=False)
    op.create_index('ix_tasks_category_status', 'tasks', ['category', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index('ix_tasks_category_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_category'), table_name='tasks')
    op.drop_table('tasks')
    sa.Enum(name='task_priority_enum').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='task_status_enum').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='task_subtype_enum').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='task_category_enum').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
