"""add time_entries and pomodoro_preferences tables

Revision ID: 7bfa2c600f7b
Revises: 2cf102f64616
Create Date: 2026-05-01 20:39:35.960332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bfa2c600f7b'
down_revision: Union[str, Sequence[str], None] = '2cf102f64616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pomodoro_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('focus_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('short_break_seconds', sa.Integer(), nullable=False),
    sa.Column('long_break_seconds', sa.Integer(), nullable=False),
    sa.Column('cycles_before_long_break', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('pomodoro_focus', 'pomodoro_short_break', 'pomodoro_long_break', 'free_timer', name='time_entry_type_enum'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_started_at'), 'time_entries', ['started_at'], unique=False)
    op.create_index('ix_time_entries_started_type', 'time_entries', ['started_at', 'type'], unique=False)
    op.create_index(op.f('ix_time_entries_task_id'), 'time_entries', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_entries_task_id'), table_name='time_entries')
    op.drop_index('ix_time_entries_started_type', table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_started_at'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_table('pomodoro_preferences')
    sa.Enum(name='time_entry_type_enum').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
