"""create applications table

Revision ID: c6d9a05ae9e9
Revises: 
Create Date: 2026-04-22 20:18:03.402090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d9a05ae9e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('contract_type', sa.Enum('Alternance', 'CDI', 'CDD', 'Stage', 'Freelance', 'Other', name='contract_type_enum'), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('New', 'Applied', 'Followed up', 'Interview', 'Accepted', 'Rejected', 'No response', 'Dismissed', name='application_status_enum'), nullable=False),
    sa.Column('cv_sent', sa.Boolean(), nullable=False),
    sa.Column('follow_up_done', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('last_contact', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    sa.Enum(name='application_status_enum').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='contract_type_enum').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
